---
name: Check

on:
  pull_request:
    branches: [main]

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt

      - name: Run unit tests
        run: pytest

  spellcheck:

    runs-on: ubuntu-latest

    steps:
      - uses: gevhaz/word-warden@v1.0.0
